/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activities
         * @description Activities newest first, optionally only one sport.
         */
        get: operations["listActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare
         * @description Compare two activities. Pass them in either order; the earlier one is the baseline.
         */
        get: operations["compareActivities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activity_id}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity Details */
        get: operations["getActivityDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["getSyncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Sync
         * @description Fetch new activities from Garmin now.
         */
        post: operations["runSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan
         * @description Estimate race time from recent runs and lay out the weeks until race day.
         *
         *     Nothing is stored: the plan is recalculated from your latest runs on every request.
         */
        get: operations["buildTrainingPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityComparison
         * @description Two runs side by side. The runs are put in date order and changes run earlier -> later.
         */
        ActivityComparison: {
            earlier: components["schemas"]["ActivitySummary"];
            later: components["schemas"]["ActivitySummary"];
            /** Days Between */
            days_between: number;
            /** Metrics */
            metrics: components["schemas"]["MetricComparison"][];
        };
        /**
         * ActivityDetails
         * @description Everything Garmin recorded for one activity, grouped into labelled sections.
         */
        ActivityDetails: {
            /** Id */
            id: number;
            /** Sections */
            sections: components["schemas"]["DetailSection"][];
        };
        /** ActivityPage */
        ActivityPage: {
            /** Items */
            items: components["schemas"]["ActivitySummary"][];
            /** Total */
            total: number;
        };
        /** ActivitySummary */
        ActivitySummary: {
            /** Id */
            id: number;
            /** Garmin Id */
            garmin_id: number;
            /** Name */
            name: string | null;
            /** Sport */
            sport: string;
            /** Activity Type */
            activity_type: string;
            /**
             * Start Time Local
             * Format: date-time
             */
            start_time_local: string;
            /** Distance Mi */
            distance_mi: number | null;
            /** Duration S */
            duration_s: number | null;
            /** Moving Time S */
            moving_time_s: number | null;
            /** Avg Pace S Per Mi */
            avg_pace_s_per_mi: number | null;
            /** Elevation Gain Ft */
            elevation_gain_ft: number | null;
            /** Avg Hr */
            avg_hr: number | null;
            /** Max Hr */
            max_hr: number | null;
            /** Avg Cadence */
            avg_cadence: number | null;
            /** Avg Power */
            avg_power: number | null;
            /** Avg Stride M */
            avg_stride_m: number | null;
            /** Aerobic Te */
            aerobic_te: number | null;
            /** Anaerobic Te */
            anaerobic_te: number | null;
            /** Calories */
            calories: number | null;
        };
        /** DetailItem */
        DetailItem: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number | string;
            /** Display */
            display: string;
        };
        /** DetailSection */
        DetailSection: {
            /** Title */
            title: string;
            /** Items */
            items: components["schemas"]["DetailItem"][];
        };
        /**
         * Effort
         * @description The run (or the stretch of a run) the fitness estimate came from.
         */
        Effort: {
            /** Activity Id */
            activity_id: number;
            /** Activity Name */
            activity_name: string | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Label */
            label: string;
            /** Distance Mi */
            distance_mi: number;
            /** Time S */
            time_s: number;
            /** Vdot */
            vdot: number;
        };
        /** GarminProblem */
        GarminProblem: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /** Version */
            version: string;
        };
        /** MetricComparison */
        MetricComparison: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Earlier */
            earlier: number | null;
            /** Later */
            later: number | null;
            /** Change */
            change: number | null;
            /** Percent Change */
            percent_change: number | null;
            /** Better */
            better: ("higher" | "lower") | null;
            /** Verdict */
            verdict: ("improved" | "declined" | "unchanged") | null;
            /** Summary */
            summary: string | null;
        };
        /** PaceZone */
        PaceZone: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Purpose */
            purpose: string;
            /** Fast S Per Mi */
            fast_s_per_mi: number;
            /** Slow S Per Mi */
            slow_s_per_mi: number;
        };
        /** PlanWeek */
        PlanWeek: {
            /** Number */
            number: number;
            /**
             * Phase
             * @enum {string}
             */
            phase: "base" | "build" | "peak" | "taper";
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Total Mi */
            total_mi: number;
            /** Workouts */
            workouts: components["schemas"]["Workout"][];
        };
        /**
         * RecentTraining
         * @description What your recent running looks like, averaged over the runs used.
         */
        RecentTraining: {
            /** Run Count */
            run_count: number;
            /** Days Covered */
            days_covered: number;
            /** Weekly Mi */
            weekly_mi: number;
            /** Runs Per Week */
            runs_per_week: number;
            /** Longest Run Mi */
            longest_run_mi: number;
            /** Avg Pace S Per Mi */
            avg_pace_s_per_mi: number | null;
            /** Avg Hr */
            avg_hr: number | null;
            /** Avg Cadence */
            avg_cadence: number | null;
            /** Avg Stride M */
            avg_stride_m: number | null;
            /** Stale */
            stale: boolean;
        };
        /** SyncResultOut */
        SyncResultOut: {
            /** Added */
            added: number;
            /** Updated */
            updated: number;
            /** Total */
            total: number;
        };
        /** SyncStatus */
        SyncStatus: {
            /** Configured */
            configured: boolean;
            /** Display Name */
            display_name: string | null;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Activity Count */
            activity_count: number;
        };
        /** TrainingPlan */
        TrainingPlan: {
            /**
             * Race
             * @enum {string}
             */
            race: "5k" | "10k" | "20k" | "half_marathon" | "marathon";
            /** Race Label */
            race_label: string;
            /**
             * Race Date
             * Format: date
             */
            race_date: string;
            /** Race Distance Mi */
            race_distance_mi: number;
            /** Weeks Until Race */
            weeks_until_race: number;
            fitness: components["schemas"]["Effort"];
            /** Predicted Time S */
            predicted_time_s: number;
            /** Predicted Pace S Per Mi */
            predicted_pace_s_per_mi: number;
            /** Projected Vdot */
            projected_vdot: number;
            /** Projected Time S */
            projected_time_s: number;
            /** Projected Pace S Per Mi */
            projected_pace_s_per_mi: number;
            recent: components["schemas"]["RecentTraining"];
            /** Paces */
            paces: components["schemas"]["PaceZone"][];
            /** Weeks */
            weeks: components["schemas"]["PlanWeek"][];
            /** Notes */
            notes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Workout */
        Workout: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "easy" | "strides" | "long" | "threshold" | "intervals" | "race_pace" | "race";
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Distance Mi */
            distance_mi: number;
            /** Pace Zone */
            pace_zone: string;
            /** Fast S Per Mi */
            fast_s_per_mi: number;
            /** Slow S Per Mi */
            slow_s_per_mi: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listActivities: {
        parameters: {
            query?: {
                sport?: ("run" | "bike" | "other") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compareActivities: {
        parameters: {
            query: {
                /** @description Id of one activity */
                a: number;
                /** @description Id of the other activity */
                b: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getActivityDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getSyncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
        };
    };
    runSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultOut"];
                };
            };
            /** @description Garmin login or fetch failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GarminProblem"];
                };
            };
        };
    };
    buildTrainingPlan: {
        parameters: {
            query: {
                /** @description What you're training for */
                race: "5k" | "10k" | "20k" | "half_marathon" | "marathon";
                /** @description Race day, YYYY-MM-DD */
                race_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
